"""update release date

Revision ID: 7ae026599573
Revises: 7f01a550ffc3
Create Date: 2025-07-20 16:38:29.219617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae026599573'
down_revision: Union[str, Sequence[str], None] = '7f01a550ffc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapters', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chapters', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
