"""add type

Revision ID: f8e121adec5a
Revises: 5b2ce9e0b963
Create Date: 2025-07-13 13:54:39.515032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8e121adec5a'
down_revision: Union[str, Sequence[str], None] = '5b2ce9e0b963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    """Upgrade schema."""
     # 1. Create the enum types
    op.execute("CREATE TYPE userrole AS ENUM ('admin', 'user', 'premium', 'guest')")
    op.execute("CREATE TYPE userstatus AS ENUM ('pending', 'active', 'deactive', 'banned')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'user', 'premium', 'guest', name='userrole'), nullable=True))
    op.add_column('users', sa.Column('user_status', sa.Enum('pending', 'active', 'deactive', 'banned', name='userstatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_status')
    op.drop_column('users', 'role')


    op.execute("DROP TYPE userstatus")
    op.execute("DROP TYPE userrole")
    # ### end Alembic commands ###
